### ISSUE TITLE
Normalize file names

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xdlang#15]
@celavek I'd like to suggest that we follow @tmccombs's lead in how we name files:

```
$ tree exercises/gigasecond/
exercises/gigasecond/
├── gigasecond.d # this is a stub file, because it's an early exercise
├── gigasecond_example.d
└── gigasecond_test.d
```

let `$SLUG` represent the directory name, but with underscores instead of hyphens.

- `$SLUG_example.d`
- `$SLUG_test.d`

I'll prepare a PR with this now.

**Comment by kytrinyx** [comment]
Actually, I think that @tmccombs used the first part of the exercise name before the hyphen. That also works.

**Comment by celavek** [comment]
The underscore works for the example file I think. 
I have not gone that route as there is no separation between the test and implementation files in D, 
the tests are part of the code; so to me the __test_ seems a bit confusing as it kind of suggests a separate implementation file.

**Comment by kytrinyx** [comment]
Ah! I had no idea. In that case, @tmccombs what do you think of going the other way and not having _test, and in the SETUP.md say that people should solve in the same file.

**Comment by tmccombs** [comment]
I think that is a good idea. I was following the pattern of other exercism exercises, but in D the idiom is to put the tests in the same file, so it makes sense to do that.

**Comment by kytrinyx** [comment]
@tmccombs @celavek What should the example file be called? `$SLUG_example.d` or just `example.d`?

The only place it would matter, I think, is if we get some sort of continuous integration running where the tests would need to run against the example file.

Another question is what to do about the stub solutions in `gigasecond`, `rna-transcription`, and `raindrops`. Should the stub be included in the implementation+test file?

Should `hello-world` have a stub?

**Comment by celavek** [comment]
I am for the ``` $SLUG_example.d``` in the light of CI, which I thought was implemented already 😃.

I did not provide any stubs as I followed the C++ example and I think that is a good idea to start with correcting some compilation errors first so one gets a feeling of how the conversation with the compiler and the language will proceed.
 
So I am for removing the stubs completely.

**Comment by kytrinyx** [comment]
> in the light of CI, which I thought was implemented already

We have some very, very light CI that just lints the format of the project (makes sure the config.json is valid, and that we have a test file and example solution), stuff like that.

> So I am for removing the stubs completely.

That sounds fine to me. I'll do that.
