### ISSUE TITLE
History messed up in PR 19

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xdlang#21]
@tmccombs @celavek @wilzbach @canweriotnow @joeltaylor @dkinzer - you all have forks, this might be relevant to you.

I've reset the master branch to what it was before pull request #19 was merged, as the pull request included a huge number of commits that should not have gone into master.

I'm going to recreate the pull request.

If you are working on something please do the following:

**Find out what the remote name is for this repository (not your fork).**

Typical names are `origin` or `upstream`, but it could be anything you've decided.

```
$ git remote -v
origin	git@github.com:kytrinyx/xdlang.git (fetch)
origin	git@github.com:kytrinyx/xdlang.git (push)
upstream	git@github.com:exercism/xdlang.git (fetch)
upstream	git@github.com:exercism/xdlang.git (push)
```

I'll be using `upstream` in the examples below.

**Make sure you have the most recent version of the upstream master.**

```
$ git fetch upstream master
$ git checkout master
$ git reset --hard upstream/master
```

**For any branch you are currently working on, reconstruct it**

Let's say you have a branch called `config-format`

Rename the branch:

```
$ git branch -m config-format config-format-bk
```

Now check out a fresh config-format off of master:

```
$ git checkout -b config-format master
```

Find the commits you're interested:

```
$ git log --pretty="oneline"
35e70f2e3291bd5d68658fd29738f79ac10242d4 Document filenaming conventions in README
add4fcecb1577f7572e972e7937f29eeffb1164c Rename bob example file
1f845f23ce8a69fc0181431c9ea1448857adfc0a Normalize circular-buffer filenames
35d06b395eab89b3a5dd21934fab338eb1624a3d Normalize crypto-square filenames
...
```

Cherry-pick them:

```
$ git cherry-pick 35e70f2e3291bd5d68658fd29738f79ac10242d4
```

**Comment by kytrinyx** [comment]
If you have any questions about workflow, please don't hesitate to ask.

**Comment by celavek** [comment]
The whole mess is my fault. I apologize for any inconvenience caused.

I'm still confused a bit how I ended up with that. I thought all those commits were already in the master branch

**Comment by kytrinyx** [comment]
I did some rebasing and editing when I merged those commits, so while the contents are in master, those exact commits (SHA1s) are not.

In general I try to never assume that what I have on my local master is what is on the remote master. Whenever I start new work, I first reset my master to the upstream one:

```
git checkout master
git fetch upstream master
git reset --hard upstream/master
```

Then I branch off of that.

**Comment by dkinzer** [comment]
ok, i'll kill my old fork

**Comment by kytrinyx** [comment]
You don't have to kill your fork, just reset --hard to the upstream/master :)

... or kill it and refork, if that's easier.

**Comment by kytrinyx** [comment]
I'm going to close this, as it seems like we've got it sorted.
